language: objective-c
before_install:
- brew update
- brew unlink xctool
- brew install xctool
script: xctool -project ./src/runtime/ProtocolBuffers.xcodeproj -sdk iphonesimulator -scheme ProtocolBuffers build test
